name: Docker

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 5,5 * * *"
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.compare.outputs.RELEASE_VERSION }}
      CURRENT_VERSION: ${{ steps.compare.outputs.CURRENT_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Get latest release
        id: zerotierone
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: zerotier
          repo: ZeroTierOne
          excludes: prerelease, draft

      - name: Compare
        id: compare
        run: |
          echo "RELEASE_VERSION=${{ steps.zerotierone.outputs.release }}" >> $GITHUB_OUTPUT \
          && echo "CURRENT_VERSION=$(cat ZEROTIER_VERSION)" >> $GITHUB_OUTPUT

  build:
    needs: check
    if: ${{ needs.check.outputs.RELEASE_VERSION != needs.check.outputs.CURRENT_VERSION }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: ${{ needs.check.outputs.RELEASE_VERSION }},latest
          images: jongsx/zerotier-moon,ghcr.io/trganda/zerotier-moon

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/ppc64le,linux/s390x,linux/arm64,linux/arm/v7,linux/arm64/v8
          builder: ${{ steps.buildx.outputs.name }}

      - name: Update ZEROTIER_VERSION
        run: |
          echo "$RELEASE_VERSION" > ZEROTIER_VERSION

      - name: Commit & Push changes
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
